name: 'Newman Action'
description: 'Run Postman collections via Newman'
author: 'Matt Ball'
branding:
  icon: 'check-square'  
  color: 'orange'
inputs:
  collection:
    description: 'Collection to use'
    default: 'postman_collection.json'
  environment:
    description: 'Environment to use'
    default: 'postman_environment.json'
runs:
  using: 'node12'
  main: 'index.js'
